[[override]]
  name = "github.com/pulumi/pulumi"
  revision = "315ae8b85ffe4b6033e2e4266c3f94085d0f985e"

[[override]]
  name = "github.com/pulumi/pulumi-terraform"
  revision = "6c3ee3e2a025764c50871b17d6bc622665902361"

[[override]]
  name = "github.com/hashicorp/terraform"
  source = "github.com/pulumi/terraform"
  branch = "pulumi-master"

[[override]]
  name = "github.com/terraform-providers/terraform-provider-aws"
  source = "github.com/pulumi/terraform-provider-aws"
  branch = "pulumi-master"
