[[override]]
  name = "github.com/pulumi/pulumi"
  version = "0.9.5"

[[override]]
  name = "github.com/pulumi/pulumi-terraform"
  version = "0.9.5"

[[override]]
  name = "github.com/hashicorp/terraform"
  source = "github.com/pulumi/terraform"
  branch = "pulumi-master"

[[override]]
  name = "github.com/terraform-providers/terraform-provider-aws"
  source = "github.com/pulumi/terraform-provider-aws"
  branch = "pulumi-master"
