[tools]
"github:pulumi/pulumi-archive" = "0.3.6"
"github:pulumi/pulumi-tls" = "5.2.3"
"github:pulumi/pulumi-github" = "6.10.1"
"github:pulumi/pulumi-kubernetes" = "4.24.1"
"github:pulumi/pulumi-null" = "0.0.14"
"github:pulumi/pulumi-local" = "0.1.6"
"github:pulumi/pulumi-random" = "4.18.5"
"github:pulumi/pulumi-std" = "2.2.0"
"github:pulumi/pulumi-converter-terraform" = "1.2.4"
