name: "Test Provider"

on:
   workflow_call:
     inputs:
       version:
         required: true
         type: string
         description: Version of the provider to test

env:
  PR_COMMIT_SHA: ${{ github.event.client_payload.pull_request.head.sha }}
  AWS_REGION: us-west-2
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  NUGET_PUBLISH_KEY: ${{ secrets.NUGET_PUBLISH_KEY }}
  OIDC_ROLE_ARN: ${{ secrets.OIDC_ROLE_ARN }}
  PUBLISH_REPO_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
  PUBLISH_REPO_USERNAME: ${{ secrets.OSSRH_USERNAME }}
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  PULUMI_API: https://api.pulumi-staging.io
  PULUMI_GO_DEP_ROOT: ${{ github.workspace }}/..
  PULUMI_LOCAL_NUGET: ${{ github.workspace }}/nuget
  PULUMI_MISSING_DOCS_ERROR: "true"
  PYPI_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
  PYPI_USERNAME: __token__
  SIGNING_KEY: ${{ secrets.JAVA_SIGNING_KEY }}
  SIGNING_KEY_ID: ${{ secrets.JAVA_SIGNING_KEY_ID }}
  SIGNING_PASSWORD: ${{ secrets.JAVA_SIGNING_PASSWORD }}
  TF_APPEND_USER_AGENT: pulumi

jobs:
  test:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    env:
      PROVIDER_VERSION: ${{ inputs.version }}
    steps:
    # Run as first step so we don't delete things that have just been installed
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
      with:
        tool-cache: false
        swap-storage: false
        dotnet: false
    - name: Checkout Repo
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        ref: ${{ env.PR_COMMIT_SHA }}
        submodules: true
        persist-credentials: false
    - name: Checkout p/examples
      if: matrix.testTarget == 'pulumiExamples'
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: pulumi/examples
        path: p-examples
    - name: Setup tools
      uses: ./.github/actions/setup-tools
      with:
        tools: pulumictl, pulumicli, ${{ matrix.language }}
    - name: Prepare local workspace
      run: make prepare_local_workspace
    - name: Download bin
      uses: ./.github/actions/download-bin
    - name: Download SDK
      uses: ./.github/actions/download-sdk
      with:
        language: ${{ matrix.language }}
    - name: Restore makefile progress
      run: make --touch provider schema build_${{ matrix.language }}
    - name: Update path
      run: echo "${{ github.workspace }}/bin" >> "$GITHUB_PATH"
    - name: Install Python deps
      if: matrix.language == 'python'
      run: |-
        pip3 install virtualenv==20.0.23
        pip3 install pipenv
    - name: Install dependencies
      run: make install_${{ matrix.language}}_sdk
    - name: Install gotestfmt
      uses: GoTestTools/gotestfmt-action@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        version: v2.5.0
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-region: ${{ env.AWS_REGION }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        role-duration-seconds: 7200
        role-session-name: aws@githubActions
        role-to-assume: ${{ secrets.AWS_CI_ROLE_ARN }}
    - name: Make upstream
      run: make upstream
    - name: Run tests
      if: matrix.testTarget == 'local'
      run: cd examples && go test -v -count=1 -cover -timeout 2h -tags=${{ matrix.language }} -skip TestPulumiExamples -parallel 4 .
    - name: Run pulumi/examples tests
      if: matrix.testTarget == 'pulumiExamples'
      run: cd examples && go test -v -count=1 -cover -timeout 2h -tags=${{ matrix.language }} -run TestPulumiExamples -parallel 4 .
    strategy:
      fail-fast: false
      matrix:
        language:
        - nodejs
        - python
        - dotnet
        - go
        - java
        testTarget: [local]
  go_test_shim:
      name: Run test of provider shim
      runs-on: ubuntu-latest
      steps:
          - name: Free Disk Space (Ubuntu)
            uses: jlumbroso/free-disk-space@main
            with:
              swap-storage: false
              tool-cache: false
          - name: Checkout Repo
            uses: actions/checkout@v4
            with:
              ref: ${{ env.PR_COMMIT_SHA }}
              submodules: true
          - uses: pulumi/provider-version-action@v1
            with:
              set-env: PROVIDER_VERSION
          - name: Setup tools
            uses: ./.github/actions/setup-tools
            with:
              tools: pulumictl, pulumi, go
          - name: Prepare local workspace
            run: make prepare_local_workspace
          - name: go test
            run: |
              cd upstream
              go get github.com/hashicorp/aws-sdk-go-base@v1.1.0
              cd shim
              go test -v -coverprofile="coverage.txt" .
          - env:
              CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
            name: Upload coverage reports to Codecov
            uses: codecov/codecov-action@v4
      timeout-minutes: 60
  upstream_lint:
      name: Run upstream provider-lint
      runs-on: ubuntu-latest
      steps:
          - name: Free Disk Space (Ubuntu)
            uses: jlumbroso/free-disk-space@main
            with:
              swap-storage: false
              tool-cache: false
          - name: Checkout Repo
            uses: actions/checkout@v4
            with:
              ref: ${{ env.PR_COMMIT_SHA }}
              submodules: true
          - name: Install Go
            uses: actions/setup-go@v5
            with:
              cache: false
              go-version: 1.23.x
          - name: Prepare local workspace
            run: make prepare_local_workspace
          - name: upstream lint
            run: |
              cd upstream
              make provider-lint
      timeout-minutes: 60

