env:
  AWS_REGION: us-west-2
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  NUGET_PUBLISH_KEY: ${{ secrets.NUGET_PUBLISH_KEY }}
  PROVIDER: aws
  PUBLISH_REPO_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
  PUBLISH_REPO_URL: https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/
  PUBLISH_REPO_USERNAME: ${{ secrets.OSSRH_USERNAME }}
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  PULUMI_API: https://api.pulumi-staging.io
  PULUMI_EXTRA_MAPPING_ERROR: true
  PULUMI_GO_DEP_ROOT: ${{ github.workspace }}/..
  PULUMI_LOCAL_NUGET: ${{ github.workspace }}/nuget
  PULUMI_MISSING_DOCS_ERROR: true
  PULUMI_MISSING_MAPPING_ERROR: true
  PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
  SIGNING_KEY: ${{ secrets.JAVA_SIGNING_KEY }}
  SIGNING_KEY_ID: ${{ secrets.JAVA_SIGNING_KEY_ID }}
  SIGNING_PASSWORD: ${{ secrets.JAVA_SIGNING_PASSWORD }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  TRAVIS_OS_NAME: linux
  UPSTREAM_PROVIDER_MAJOR_VERSION: ""
  UPSTREAM_PROVIDER_ORG: pulumi
  UPSTREAM_PROVIDER_REPO: terraform-provider-aws
jobs:
  update_upstream_provider:
    name: update-upstream_provider
    runs-on: ubuntu-latest
    steps:
    - id: run-url
      name: Create URL to the run output
      run: echo ::set-output
        name=run-url::https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Unshallow clone for tags
      run: git fetch --prune --unshallow --tags
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{matrix.goversion}}
    - name: Install pulumictl
      uses: jaxxstorm/action-install-gh-release@v1.2.0
      with:
        repo: pulumi/pulumictl
    - name: Install Pulumi CLI
      uses: pulumi/action-install-pulumi-cli@v2
    - name: Setup DotNet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{matrix.dotnetversion}}
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: ${{matrix.nodeversion}}
        registry-url: https://registry.npmjs.org
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.pythonversion}}
    - name: Get upstream provider sha
      run: echo "UPSTREAM_PROVIDER_SHA=$(curl https://api.github.com/repos/${{
        env.UPSTREAM_PROVIDER_ORG }}/${{ env.UPSTREAM_PROVIDER_REPO
        }}/git/ref/tags/v${{ github.event.inputs.version }} | jq .object.sha
        -r)" >> $GITHUB_ENV
    - if: ${{ hashFiles('provider/shim/go.mod') != '' }}
      name: Update shim/go.mod
      run: cd provider/shim && go mod edit -require github.com/${{
        env.UPSTREAM_PROVIDER_ORG }}/${{ env.UPSTREAM_PROVIDER_REPO }}${{
        env.UPSTREAM_PROVIDER_MAJOR_VERSION }}@${{ env.UPSTREAM_PROVIDER_SHA }}
        && go mod tidy
    - name: Update go.mod
      run: cd provider && go mod edit -require github.com/${{
        env.UPSTREAM_PROVIDER_ORG }}/${{ env.UPSTREAM_PROVIDER_REPO }}${{
        env.UPSTREAM_PROVIDER_MAJOR_VERSION }}@${{ env.UPSTREAM_PROVIDER_SHA }}
        && go mod tidy
    - run: make tfgen
    - run: make build_sdks
    - if: ${{ !github.event.inputs.linked_issue_number }}
      name: Create PR (no linked issue)
      uses: peter-evans/create-pull-request@v3.12.0
      with:
        author: pulumi-bot <bot@pulumi.com>
        base: master
        body: This pull request was generated automatically by the
          update-upstream-provider workflow in this repository.
        branch: pulumi-bot/v${{ github.event.inputs.version }}-${{ github.run_id}}
        commit-message: Update ${{ env.UPSTREAM_PROVIDER_REPO }} to v${{
          github.event.inputs.version }}
        committer: pulumi-bot <bot@pulumi.com>
        labels: impact/no-changelog-required
        team-reviewers: platform-integrations
        title: Update ${{ env.UPSTREAM_PROVIDER_REPO }} to v${{
          github.event.inputs.version }}
        token: ${{ secrets.PULUMI_BOT_TOKEN }}
    - if: ${{ github.event.inputs.linked_issue_number }}
      name: Create PR (with linked issue)
      uses: peter-evans/create-pull-request@v3.12.0
      with:
        author: pulumi-bot <bot@pulumi.com>
        base: master
        body: >-
          Fixes #${{ github.event.inputs.linked_issue_number }}


          This pull request was generated automatically by the update-upstream-provider workflow in this repository.
        branch: pulumi-bot/v${{ github.event.inputs.version }}-${{ github.run_id}}
        commit-message: Update ${{ env.UPSTREAM_PROVIDER_REPO }} to v${{
          github.event.inputs.version }}
        committer: pulumi-bot <bot@pulumi.com>
        labels: impact/no-changelog-required
        team-reviewers: platform-integrations
        title: Update ${{ env.UPSTREAM_PROVIDER_REPO }} to v${{
          github.event.inputs.version }}
        token: ${{ secrets.PULUMI_BOT_TOKEN }}
    - if: ${{ failure() && github.event.inputs.linked_issue_number }}
      name: Comment on failed attempt
      uses: jungwinter/comment@v1
      with:
        body: >-
          Failed to automatically update upstream provider (probably beacuse of
          new resources or data sources, which must be mapped manually).


          For more details, see: ${{ steps.run-url.outputs.run-url }}
        issue_number: ${{ github.event.inputs.linked_issue_number }}
        token: ${{ secrets.PULUMI_BOT_TOKEN }}
        type: create
    strategy:
      fail-fast: true
      matrix:
        dotnetversion:
        - 3.1.301
        goversion:
        - 1.18.x
        nodeversion:
        - 14.x
        pythonversion:
        - "3.7"
name: Update upstream provider
on:
  workflow_dispatch:
    inputs:
      linked_issue_number:
        description: The issue number of a PR in this repository to which the generated
          pull request should be linked.
        required: false
        type: string
      version:
        description: The new version of the upstream provider. Do not include the 'v'
          prefix.
        required: true
        type: string
